name: youtube_video_player
description: A versatile Flutter package that allows you to easily integrate a YouTube player into your Flutter applications.
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=2.0.0 <3.0.0"

dependencies:
  audio_video_progress_bar: ^2.0.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  get: ^4.6.6
  http: ^1.1.0
  screen_brightness: ^0.2.2+1
  subtitle: ^0.1.0
  video_player: ^2.8.1
  wakelock: ^0.5.0+2
  wakelock_windows: ^0.2.1
  youtube_explode_dart: ^2.0.2
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/icons/

dependency_overrides:
  win32: ^3.0.0
